POST http://api.weatherapi.com/v1/current.json?key=1ba50f84ca424deba5f233704242711&q=bulk HTTP/1.1
Host: api.weatherapi.com
Content-Type: application/json

{
    "locations": [
        {
            "q": "Pirapora do norte"
        }
    ]
}